services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=expensesDB'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=username'
    ports:
      - '5432:5432'
